package first.pojo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 5.proto



public final class AccessLogProto {
    private AccessLogProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface AccessLogOrBuilder extends
            // @@protoc_insertion_point(interface_extends:AccessLog)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string ip = 1;</code>
         * @return The ip.
         */
        String getIp();
        /**
         * <code>string ip = 1;</code>
         * @return The bytes for ip.
         */
        com.google.protobuf.ByteString
        getIpBytes();

        /**
         * <code>string time = 2;</code>
         * @return The time.
         */
        String getTime();
        /**
         * <code>string time = 2;</code>
         * @return The bytes for time.
         */
        com.google.protobuf.ByteString
        getTimeBytes();

        /**
         * <code>string type = 3;</code>
         * @return The type.
         */
        String getType();
        /**
         * <code>string type = 3;</code>
         * @return The bytes for type.
         */
        com.google.protobuf.ByteString
        getTypeBytes();

        /**
         * <code>string api = 4;</code>
         * @return The api.
         */
        String getApi();
        /**
         * <code>string api = 4;</code>
         * @return The bytes for api.
         */
        com.google.protobuf.ByteString
        getApiBytes();

        /**
         * <code>string num = 5;</code>
         * @return The num.
         */
        String getNum();
        /**
         * <code>string num = 5;</code>
         * @return The bytes for num.
         */
        com.google.protobuf.ByteString
        getNumBytes();
    }
    /**
     * <pre>
     * 消息结构定义
     * </pre>
     *
     * Protobuf type {@code AccessLog}
     */
    public static final class AccessLog extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:AccessLog)
            AccessLogOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use AccessLog.newBuilder() to construct.
        private AccessLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private AccessLog() {
            ip_ = "";
            time_ = "";
            type_ = "";
            api_ = "";
            num_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new AccessLog();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private AccessLog(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            ip_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            time_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            type_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            api_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            num_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return AccessLogProto.internal_static_AccessLog_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return AccessLogProto.internal_static_AccessLog_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            AccessLog.class, Builder.class);
        }

        public static final int IP_FIELD_NUMBER = 1;
        private volatile Object ip_;
        /**
         * <code>string ip = 1;</code>
         * @return The ip.
         */
        @Override
        public String getIp() {
            Object ref = ip_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                ip_ = s;
                return s;
            }
        }
        /**
         * <code>string ip = 1;</code>
         * @return The bytes for ip.
         */
        @Override
        public com.google.protobuf.ByteString
        getIpBytes() {
            Object ref = ip_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                ip_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TIME_FIELD_NUMBER = 2;
        private volatile Object time_;
        /**
         * <code>string time = 2;</code>
         * @return The time.
         */
        @Override
        public String getTime() {
            Object ref = time_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                time_ = s;
                return s;
            }
        }
        /**
         * <code>string time = 2;</code>
         * @return The bytes for time.
         */
        @Override
        public com.google.protobuf.ByteString
        getTimeBytes() {
            Object ref = time_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                time_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 3;
        private volatile Object type_;
        /**
         * <code>string type = 3;</code>
         * @return The type.
         */
        @Override
        public String getType() {
            Object ref = type_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                type_ = s;
                return s;
            }
        }
        /**
         * <code>string type = 3;</code>
         * @return The bytes for type.
         */
        @Override
        public com.google.protobuf.ByteString
        getTypeBytes() {
            Object ref = type_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int API_FIELD_NUMBER = 4;
        private volatile Object api_;
        /**
         * <code>string api = 4;</code>
         * @return The api.
         */
        @Override
        public String getApi() {
            Object ref = api_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                api_ = s;
                return s;
            }
        }
        /**
         * <code>string api = 4;</code>
         * @return The bytes for api.
         */
        @Override
        public com.google.protobuf.ByteString
        getApiBytes() {
            Object ref = api_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                api_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int NUM_FIELD_NUMBER = 5;
        private volatile Object num_;
        /**
         * <code>string num = 5;</code>
         * @return The num.
         */
        @Override
        public String getNum() {
            Object ref = num_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                num_ = s;
                return s;
            }
        }
        /**
         * <code>string num = 5;</code>
         * @return The bytes for num.
         */
        @Override
        public com.google.protobuf.ByteString
        getNumBytes() {
            Object ref = num_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                num_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getIpBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
            }
            if (!getTimeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, time_);
            }
            if (!getTypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
            }
            if (!getApiBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, api_);
            }
            if (!getNumBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, num_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getIpBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
            }
            if (!getTimeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, time_);
            }
            if (!getTypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
            }
            if (!getApiBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, api_);
            }
            if (!getNumBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, num_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof AccessLog)) {
                return super.equals(obj);
            }
            AccessLog other = (AccessLog) obj;

            if (!getIp()
                    .equals(other.getIp())) return false;
            if (!getTime()
                    .equals(other.getTime())) return false;
            if (!getType()
                    .equals(other.getType())) return false;
            if (!getApi()
                    .equals(other.getApi())) return false;
            if (!getNum()
                    .equals(other.getNum())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + IP_FIELD_NUMBER;
            hash = (53 * hash) + getIp().hashCode();
            hash = (37 * hash) + TIME_FIELD_NUMBER;
            hash = (53 * hash) + getTime().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType().hashCode();
            hash = (37 * hash) + API_FIELD_NUMBER;
            hash = (53 * hash) + getApi().hashCode();
            hash = (37 * hash) + NUM_FIELD_NUMBER;
            hash = (53 * hash) + getNum().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static AccessLog parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static AccessLog parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static AccessLog parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static AccessLog parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static AccessLog parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static AccessLog parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static AccessLog parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static AccessLog parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static AccessLog parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static AccessLog parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static AccessLog parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static AccessLog parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(AccessLog prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         * 消息结构定义
         * </pre>
         *
         * Protobuf type {@code AccessLog}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:AccessLog)
                AccessLogOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return AccessLogProto.internal_static_AccessLog_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return AccessLogProto.internal_static_AccessLog_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                AccessLog.class, Builder.class);
            }

            // Construct using AccessLogProto.AccessLog.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @Override
            public Builder clear() {
                super.clear();
                ip_ = "";

                time_ = "";

                type_ = "";

                api_ = "";

                num_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return AccessLogProto.internal_static_AccessLog_descriptor;
            }

            @Override
            public AccessLog getDefaultInstanceForType() {
                return AccessLog.getDefaultInstance();
            }

            @Override
            public AccessLog build() {
                AccessLog result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public AccessLog buildPartial() {
                AccessLog result = new AccessLog(this);
                result.ip_ = ip_;
                result.time_ = time_;
                result.type_ = type_;
                result.api_ = api_;
                result.num_ = num_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }
            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }
            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }
            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof AccessLog) {
                    return mergeFrom((AccessLog)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(AccessLog other) {
                if (other == AccessLog.getDefaultInstance()) return this;
                if (!other.getIp().isEmpty()) {
                    ip_ = other.ip_;
                    onChanged();
                }
                if (!other.getTime().isEmpty()) {
                    time_ = other.time_;
                    onChanged();
                }
                if (!other.getType().isEmpty()) {
                    type_ = other.type_;
                    onChanged();
                }
                if (!other.getApi().isEmpty()) {
                    api_ = other.api_;
                    onChanged();
                }
                if (!other.getNum().isEmpty()) {
                    num_ = other.num_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                AccessLog parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (AccessLog) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object ip_ = "";
            /**
             * <code>string ip = 1;</code>
             * @return The ip.
             */
            public String getIp() {
                Object ref = ip_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    ip_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string ip = 1;</code>
             * @return The bytes for ip.
             */
            public com.google.protobuf.ByteString
            getIpBytes() {
                Object ref = ip_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    ip_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string ip = 1;</code>
             * @param value The ip to set.
             * @return This builder for chaining.
             */
            public Builder setIp(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ip_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string ip = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearIp() {

                ip_ = getDefaultInstance().getIp();
                onChanged();
                return this;
            }
            /**
             * <code>string ip = 1;</code>
             * @param value The bytes for ip to set.
             * @return This builder for chaining.
             */
            public Builder setIpBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ip_ = value;
                onChanged();
                return this;
            }

            private Object time_ = "";
            /**
             * <code>string time = 2;</code>
             * @return The time.
             */
            public String getTime() {
                Object ref = time_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    time_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string time = 2;</code>
             * @return The bytes for time.
             */
            public com.google.protobuf.ByteString
            getTimeBytes() {
                Object ref = time_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    time_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string time = 2;</code>
             * @param value The time to set.
             * @return This builder for chaining.
             */
            public Builder setTime(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                time_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string time = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearTime() {

                time_ = getDefaultInstance().getTime();
                onChanged();
                return this;
            }
            /**
             * <code>string time = 2;</code>
             * @param value The bytes for time to set.
             * @return This builder for chaining.
             */
            public Builder setTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                time_ = value;
                onChanged();
                return this;
            }

            private Object type_ = "";
            /**
             * <code>string type = 3;</code>
             * @return The type.
             */
            public String getType() {
                Object ref = type_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    type_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string type = 3;</code>
             * @return The bytes for type.
             */
            public com.google.protobuf.ByteString
            getTypeBytes() {
                Object ref = type_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    type_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string type = 3;</code>
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string type = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearType() {

                type_ = getDefaultInstance().getType();
                onChanged();
                return this;
            }
            /**
             * <code>string type = 3;</code>
             * @param value The bytes for type to set.
             * @return This builder for chaining.
             */
            public Builder setTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                type_ = value;
                onChanged();
                return this;
            }

            private Object api_ = "";
            /**
             * <code>string api = 4;</code>
             * @return The api.
             */
            public String getApi() {
                Object ref = api_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    api_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string api = 4;</code>
             * @return The bytes for api.
             */
            public com.google.protobuf.ByteString
            getApiBytes() {
                Object ref = api_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    api_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string api = 4;</code>
             * @param value The api to set.
             * @return This builder for chaining.
             */
            public Builder setApi(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                api_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string api = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearApi() {

                api_ = getDefaultInstance().getApi();
                onChanged();
                return this;
            }
            /**
             * <code>string api = 4;</code>
             * @param value The bytes for api to set.
             * @return This builder for chaining.
             */
            public Builder setApiBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                api_ = value;
                onChanged();
                return this;
            }

            private Object num_ = "";
            /**
             * <code>string num = 5;</code>
             * @return The num.
             */
            public String getNum() {
                Object ref = num_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    num_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string num = 5;</code>
             * @return The bytes for num.
             */
            public com.google.protobuf.ByteString
            getNumBytes() {
                Object ref = num_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    num_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string num = 5;</code>
             * @param value The num to set.
             * @return This builder for chaining.
             */
            public Builder setNum(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                num_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string num = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearNum() {

                num_ = getDefaultInstance().getNum();
                onChanged();
                return this;
            }
            /**
             * <code>string num = 5;</code>
             * @param value The bytes for num to set.
             * @return This builder for chaining.
             */
            public Builder setNumBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                num_ = value;
                onChanged();
                return this;
            }
            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:AccessLog)
        }

        // @@protoc_insertion_point(class_scope:AccessLog)
        private static final AccessLog DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new AccessLog();
        }

        public static AccessLog getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<AccessLog>
                PARSER = new com.google.protobuf.AbstractParser<AccessLog>() {
            @Override
            public AccessLog parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AccessLog(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<AccessLog> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<AccessLog> getParserForType() {
            return PARSER;
        }

        @Override
        public AccessLog getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_AccessLog_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_AccessLog_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\0075.proto\"M\n\tAccessLog\022\n\n\002ip\030\001 \001(\t\022\014\n\004ti" +
                        "me\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\013\n\003api\030\004 \001(\t\022\013\n\003n" +
                        "um\030\005 \001(\tB9\n\'com.itcast.flink.connectors." +
                        "kafka.protoB\016AccessLogProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_AccessLog_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_AccessLog_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_AccessLog_descriptor,
                new String[] { "Ip", "Time", "Type", "Api", "Num", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
